spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/memorize
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  liquibase:
#    enabled: false
    user: username
    password: password
    change-log: db/changelog/changelog-root.xml
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE